export const ADDINJURY = "ADDINJURY"
export const UPDATEINJURY = "UPDATEINJURY"
export const FINDINJURY = "FINDINJURY"
export const DELETEINJURY = "DELETEINJURY"
export const FINDALLINJURIES = "FINDALLINJURIES"

export const ADDINCIDENTS = "ADDINCIDENTS"
export const UPDATEINCIDENTS = "UPDATEINCIDENTS"
export const DELETEINCIDENTS = "DELETEINCIDENTS"
export const FINDINCIDENTS = "FINDINCIDENTS"
export const FINDALLINCIDENTS = "FINDALLINCIDENTS"


export const ADDDEFINEDACTION = "ADDDEFINEDACTION"
export const UPDATEDEFINEDACTION = "UPDATEDEFINEDACTION"
export const DELETEDEFINEDACTION = "DELETEDEFINEDACTION"
export const FINDDEFINEDACTION = "FINDDEFINEDACTION"
export const FINDALLDEFINEDACTION = "FINDALLDEFINEDACTION"


export const ADDREPORTS = "ADDREPORTS"
export const FINDREPORTS = "FINDREPORTS"
export const DELETEREPORTS = "DELETEREPORTS"
export const UPDATEREPORTS = "UPDATEREPORTS"
export const FINDALLREPORTS = "FINDALLREPORTS"

export const ADDACTIONS = "ADDACTION"
export const UPDATEACTIONS = "UPDATEACTIONS"
export const FINDACTIONS = "FINDACTIONS"
export const DELETEACTIONS = "DELETEACTIONS"
export const FINDALLACTIONS = "FINDALLACTIONS"